### ISSUE TITLE
New Logo for VOTEFUND [Task Request]

### ISSUE THREAD

**Issue by artjeck** [Rishi556/Votefund-iOS#1]
Hi Owner !
I am a Graphic Designer, I have Make a new Logo VOTEFUND for you, Before I publish it in Utopian-io, I need permission from you first, hopefully you like 😃 
![banner](https://user-images.githubusercontent.com/38141262/38773068-a56dce08-406e-11e8-80e4-91b67d58829b.jpg)
![color varian](https://user-images.githubusercontent.com/38141262/38773072-bafa2d2a-406e-11e8-83fd-57e04c4ff3b4.jpg)
![logotypewhitemode](https://user-images.githubusercontent.com/38141262/38773073-bb30e96e-406e-11e8-812f-fd1fa21be861.jpg)
![pw](https://user-images.githubusercontent.com/38141262/38773074-bb6716d8-406e-11e8-8eda-c7a6fc49d079.jpg)

**Comment by Rishi556** [comment]
I did not end up using this.
